/*
  BaseCore full SQL Server database script
  Scope:
  - Authentication and authorization
  - Storefront/business tables
  - System settings and seed configuration
  - Basic audit/log tables

  Notes:
  - This script is aligned with the codebase after moving auth/user storage from MongoDB to SQL Server.
  - String primary keys are used for platform/auth tables because many entities inherit from BaseCore.Common.Entity.
  - The admin account is seeded with plain-text password 'admin123' and NULL salt so the current code can still authenticate.
    After first successful login/change-password flow, you should replace it with a PBKDF2 hash generated by the application.
*/

SET NOCOUNT ON;
GO

USE master;
GO

IF DB_ID(N'BaseCoreSales') IS NULL
BEGIN
    DECLARE @DataPath NVARCHAR(4000) = CONVERT(NVARCHAR(4000), SERVERPROPERTY(N'InstanceDefaultDataPath'));
    DECLARE @LogPath NVARCHAR(4000) = CONVERT(NVARCHAR(4000), SERVERPROPERTY(N'InstanceDefaultLogPath'));
    DECLARE @Suffix NVARCHAR(32) = REPLACE(CONVERT(NVARCHAR(8), GETDATE(), 112) + N'_' + CONVERT(NVARCHAR(8), GETDATE(), 108), N':', N'');
    DECLARE @CreateDbSql NVARCHAR(MAX);

    IF @DataPath IS NULL
        SET @DataPath = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\';

    IF @LogPath IS NULL
        SET @LogPath = @DataPath;

    SET @CreateDbSql =
        N'CREATE DATABASE BaseCoreSales ON PRIMARY ' +
        N'( NAME = N''BaseCoreSales'', FILENAME = N''' + REPLACE(@DataPath, '''', '''''') + N'BaseCoreSales_' + @Suffix + N'.mdf'' ) ' +
        N'LOG ON ' +
        N'( NAME = N''BaseCoreSales_log'', FILENAME = N''' + REPLACE(@LogPath, '''', '''''') + N'BaseCoreSales_' + @Suffix + N'_log.ldf'' )';

    EXEC (@CreateDbSql);
END
GO

IF DB_ID(N'BaseCoreSales') IS NULL
BEGIN
    THROW 50001, N'Khong tao hoac khong tim thay database BaseCoreSales. Script se dung de tranh chay nham vao master.', 1;
END
GO

USE BaseCoreSales;
GO

IF DB_NAME() <> N'BaseCoreSales'
BEGIN
    THROW 50002, N'Khong chuyen duoc sang database BaseCoreSales. Script se dung de tranh tao bang trong master.', 1;
END
GO

IF SCHEMA_ID(N'dbo') IS NULL
BEGIN
    EXEC('CREATE SCHEMA dbo');
END
GO

/* =========================================================
   Core auth/user tables
   ========================================================= */

IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Users
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_Users PRIMARY KEY
            CONSTRAINT DF_Users_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Name NVARCHAR(100) NOT NULL CONSTRAINT DF_Users_Name DEFAULT (N''),
        UserName NVARCHAR(50) NOT NULL,
        Password NVARCHAR(255) NOT NULL,
        Salt VARBINARY(MAX) NULL,
        Contact NVARCHAR(255) NOT NULL CONSTRAINT DF_Users_Contact DEFAULT (N''),
        Email NVARCHAR(100) NOT NULL CONSTRAINT DF_Users_Email DEFAULT (N''),
        Phone NVARCHAR(20) NOT NULL CONSTRAINT DF_Users_Phone DEFAULT (N''),
        Position NVARCHAR(100) NOT NULL CONSTRAINT DF_Users_Position DEFAULT (N''),
        Image NVARCHAR(500) NOT NULL CONSTRAINT DF_Users_Image DEFAULT (N''),
        IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT ((1)),
        UserType INT NOT NULL CONSTRAINT DF_Users_UserType DEFAULT ((0)),
        Created DATETIME2 NOT NULL CONSTRAINT DF_Users_Created DEFAULT (SYSUTCDATETIME())
    );

    CREATE UNIQUE INDEX IX_Users_UserName ON dbo.Users(UserName);
    CREATE INDEX IX_Users_UserType ON dbo.Users(UserType);
END
GO

IF OBJECT_ID(N'dbo.Roles', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Roles
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_Roles PRIMARY KEY
            CONSTRAINT DF_Roles_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Roles_Guid DEFAULT (NEWID()),
        Name NVARCHAR(100) NOT NULL,
        Description NVARCHAR(500) NOT NULL CONSTRAINT DF_Roles_Description DEFAULT (N''),
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_Roles_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_Roles_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_Roles_IsDeleted DEFAULT ((0)),
        IsActive BIT NOT NULL CONSTRAINT DF_Roles_IsActive DEFAULT ((1)),
        RoleType INT NOT NULL CONSTRAINT DF_Roles_RoleType DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );

    CREATE UNIQUE INDEX IX_Roles_Name ON dbo.Roles(Name);
    CREATE UNIQUE INDEX IX_Roles_Guid ON dbo.Roles(Guid);
END
GO

IF OBJECT_ID(N'dbo.UserRoles', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.UserRoles
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_UserRoles PRIMARY KEY
            CONSTRAINT DF_UserRoles_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_UserRoles_Guid DEFAULT (NEWID()),
        UserId NVARCHAR(50) NOT NULL,
        RoleId NVARCHAR(50) NOT NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_UserRoles_IsActive DEFAULT ((1)),
        RoleUserId NVARCHAR(50) NULL,
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_UserRoles_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_UserRoles_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_UserRoles_IsDeleted DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL,
        CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
        CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId) REFERENCES dbo.Roles(Id),
        CONSTRAINT UQ_UserRoles_User_Role UNIQUE (UserId, RoleId)
    );

    CREATE INDEX IX_UserRoles_UserId ON dbo.UserRoles(UserId);
    CREATE INDEX IX_UserRoles_RoleId ON dbo.UserRoles(RoleId);
    CREATE UNIQUE INDEX IX_UserRoles_Guid ON dbo.UserRoles(Guid);
END
GO

IF OBJECT_ID(N'dbo.AccessTokens', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AccessTokens
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_AccessTokens PRIMARY KEY
            CONSTRAINT DF_AccessTokens_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_AccessTokens_Guid DEFAULT (NEWID()),
        UserId NVARCHAR(50) NOT NULL,
        Token NVARCHAR(MAX) NOT NULL,
        Expirated DATETIME2 NOT NULL,
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_AccessTokens_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_AccessTokens_Created DEFAULT (SYSUTCDATETIME()),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL,
        CONSTRAINT FK_AccessTokens_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
    );

    CREATE UNIQUE INDEX IX_AccessTokens_Guid ON dbo.AccessTokens(Guid);
    CREATE INDEX IX_AccessTokens_UserId ON dbo.AccessTokens(UserId);
END
GO

/* =========================================================
   Authorization platform tables
   ========================================================= */

IF OBJECT_ID(N'dbo.Modules', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Modules
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_Modules PRIMARY KEY
            CONSTRAINT DF_Modules_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Modules_Guid DEFAULT (NEWID()),
        Name NVARCHAR(100) NOT NULL,
        Description NVARCHAR(500) NOT NULL CONSTRAINT DF_Modules_Description DEFAULT (N''),
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_Modules_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_Modules_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_Modules_IsDeleted DEFAULT ((0)),
        IsActive BIT NOT NULL CONSTRAINT DF_Modules_IsActive DEFAULT ((1)),
        IsChecked BIT NOT NULL CONSTRAINT DF_Modules_IsChecked DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );

    CREATE UNIQUE INDEX IX_Modules_Name ON dbo.Modules(Name);
    CREATE UNIQUE INDEX IX_Modules_Guid ON dbo.Modules(Guid);
END
GO

IF OBJECT_ID(N'dbo.Functions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Functions
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_Functions PRIMARY KEY
            CONSTRAINT DF_Functions_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Name NVARCHAR(100) NOT NULL,
        Description NVARCHAR(500) NOT NULL CONSTRAINT DF_Functions_Description DEFAULT (N''),
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_Functions_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_Functions_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_Functions_IsDeleted DEFAULT ((0)),
        IsActive BIT NOT NULL CONSTRAINT DF_Functions_IsActive DEFAULT ((1)),
        IsChecked BIT NOT NULL CONSTRAINT DF_Functions_IsChecked DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );

    CREATE UNIQUE INDEX IX_Functions_Name ON dbo.Functions(Name);
END
GO

IF OBJECT_ID(N'dbo.ModuleFunctions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ModuleFunctions
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_ModuleFunctions PRIMARY KEY
            CONSTRAINT DF_ModuleFunctions_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ModuleFunctions_Guid DEFAULT (NEWID()),
        ModuleId NVARCHAR(50) NOT NULL,
        FunctionId NVARCHAR(50) NOT NULL,
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_ModuleFunctions_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_ModuleFunctions_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_ModuleFunctions_IsDeleted DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL,
        CONSTRAINT FK_ModuleFunctions_Modules FOREIGN KEY (ModuleId) REFERENCES dbo.Modules(Id),
        CONSTRAINT FK_ModuleFunctions_Functions FOREIGN KEY (FunctionId) REFERENCES dbo.Functions(Id),
        CONSTRAINT UQ_ModuleFunctions_Module_Function UNIQUE (ModuleId, FunctionId)
    );

    CREATE INDEX IX_ModuleFunctions_ModuleId ON dbo.ModuleFunctions(ModuleId);
    CREATE INDEX IX_ModuleFunctions_FunctionId ON dbo.ModuleFunctions(FunctionId);
    CREATE UNIQUE INDEX IX_ModuleFunctions_Guid ON dbo.ModuleFunctions(Guid);
END
GO

IF OBJECT_ID(N'dbo.RoleModuleFunctions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.RoleModuleFunctions
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_RoleModuleFunctions PRIMARY KEY
            CONSTRAINT DF_RoleModuleFunctions_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_RoleModuleFunctions_Guid DEFAULT (NEWID()),
        RoleId NVARCHAR(50) NOT NULL,
        ModuleFunctionId NVARCHAR(50) NOT NULL,
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_RoleModuleFunctions_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_RoleModuleFunctions_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_RoleModuleFunctions_IsDeleted DEFAULT ((0)),
        IsActive BIT NOT NULL CONSTRAINT DF_RoleModuleFunctions_IsActive DEFAULT ((1)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL,
        CONSTRAINT FK_RoleModuleFunctions_Roles FOREIGN KEY (RoleId) REFERENCES dbo.Roles(Id),
        CONSTRAINT FK_RoleModuleFunctions_ModuleFunctions FOREIGN KEY (ModuleFunctionId) REFERENCES dbo.ModuleFunctions(Id),
        CONSTRAINT UQ_RoleModuleFunctions_Role_ModuleFunction UNIQUE (RoleId, ModuleFunctionId)
    );

    CREATE INDEX IX_RoleModuleFunctions_RoleId ON dbo.RoleModuleFunctions(RoleId);
    CREATE INDEX IX_RoleModuleFunctions_ModuleFunctionId ON dbo.RoleModuleFunctions(ModuleFunctionId);
    CREATE UNIQUE INDEX IX_RoleModuleFunctions_Guid ON dbo.RoleModuleFunctions(Guid);
END
GO

IF OBJECT_ID(N'dbo.UserModules', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.UserModules
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_UserModules PRIMARY KEY
            CONSTRAINT DF_UserModules_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_UserModules_Guid DEFAULT (NEWID()),
        UserId NVARCHAR(50) NOT NULL,
        ModuleId NVARCHAR(50) NOT NULL,
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_UserModules_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_UserModules_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_UserModules_IsDeleted DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL,
        CONSTRAINT FK_UserModules_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
        CONSTRAINT FK_UserModules_Modules FOREIGN KEY (ModuleId) REFERENCES dbo.Modules(Id),
        CONSTRAINT UQ_UserModules_User_Module UNIQUE (UserId, ModuleId)
    );

    CREATE INDEX IX_UserModules_UserId ON dbo.UserModules(UserId);
    CREATE INDEX IX_UserModules_ModuleId ON dbo.UserModules(ModuleId);
    CREATE UNIQUE INDEX IX_UserModules_Guid ON dbo.UserModules(Guid);
END
GO

IF OBJECT_ID(N'dbo.RoleModules', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.RoleModules
    (
        RoleId NVARCHAR(50) NOT NULL,
        ModuleId NVARCHAR(50) NOT NULL,
        CONSTRAINT PK_RoleModules PRIMARY KEY (RoleId, ModuleId),
        CONSTRAINT FK_RoleModules_Roles FOREIGN KEY (RoleId) REFERENCES dbo.Roles(Id),
        CONSTRAINT FK_RoleModules_Modules FOREIGN KEY (ModuleId) REFERENCES dbo.Modules(Id)
    );
END
GO

IF OBJECT_ID(N'dbo.GroupRoleAgencies', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.GroupRoleAgencies
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_GroupRoleAgencies PRIMARY KEY
            CONSTRAINT DF_GroupRoleAgencies_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_GroupRoleAgencies_Guid DEFAULT (NEWID()),
        AgencyId NVARCHAR(50) NOT NULL,
        Name NVARCHAR(100) NOT NULL,
        Description NVARCHAR(500) NOT NULL CONSTRAINT DF_GroupRoleAgencies_Description DEFAULT (N''),
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_GroupRoleAgencies_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_GroupRoleAgencies_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_GroupRoleAgencies_IsDeleted DEFAULT ((0)),
        IsActive BIT NULL CONSTRAINT DF_GroupRoleAgencies_IsActive DEFAULT ((1)),
        RoleType INT NOT NULL CONSTRAINT DF_GroupRoleAgencies_RoleType DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );

    CREATE UNIQUE INDEX IX_GroupRoleAgencies_Guid ON dbo.GroupRoleAgencies(Guid);
    CREATE INDEX IX_GroupRoleAgencies_AgencyId ON dbo.GroupRoleAgencies(AgencyId);
END
GO

IF OBJECT_ID(N'dbo.GroupRoleAgencyModules', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.GroupRoleAgencyModules
    (
        GroupRoleAgencyId NVARCHAR(50) NOT NULL,
        ModuleId NVARCHAR(50) NOT NULL,
        CONSTRAINT PK_GroupRoleAgencyModules PRIMARY KEY (GroupRoleAgencyId, ModuleId),
        CONSTRAINT FK_GroupRoleAgencyModules_GroupRoleAgencies FOREIGN KEY (GroupRoleAgencyId) REFERENCES dbo.GroupRoleAgencies(Id),
        CONSTRAINT FK_GroupRoleAgencyModules_Modules FOREIGN KEY (ModuleId) REFERENCES dbo.Modules(Id)
    );
END
GO

IF OBJECT_ID(N'dbo.AccessTokenRoles', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AccessTokenRoles
    (
        AccessTokenId NVARCHAR(50) NOT NULL,
        RoleId NVARCHAR(50) NOT NULL,
        CONSTRAINT PK_AccessTokenRoles PRIMARY KEY (AccessTokenId, RoleId),
        CONSTRAINT FK_AccessTokenRoles_AccessTokens FOREIGN KEY (AccessTokenId) REFERENCES dbo.AccessTokens(Id),
        CONSTRAINT FK_AccessTokenRoles_Roles FOREIGN KEY (RoleId) REFERENCES dbo.Roles(Id)
    );
END
GO

/* =========================================================
   Business/store tables
   ========================================================= */

IF OBJECT_ID(N'dbo.Categories', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Categories
    (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Categories PRIMARY KEY,
        Name NVARCHAR(100) NOT NULL,
        Description NVARCHAR(500) NOT NULL CONSTRAINT DF_Categories_Description DEFAULT (N'')
    );

    CREATE UNIQUE INDEX IX_Categories_Name ON dbo.Categories(Name);
END
GO

IF OBJECT_ID(N'dbo.Products', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Products
    (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
        Name NVARCHAR(200) NOT NULL,
        Price DECIMAL(18,2) NOT NULL,
        Stock INT NOT NULL CONSTRAINT DF_Products_Stock DEFAULT ((0)),
        ImageUrl NVARCHAR(500) NOT NULL CONSTRAINT DF_Products_ImageUrl DEFAULT (N''),
        Description NVARCHAR(1000) NOT NULL CONSTRAINT DF_Products_Description DEFAULT (N''),
        CategoryId INT NOT NULL,
        CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId) REFERENCES dbo.Categories(Id)
    );

    CREATE INDEX IX_Products_CategoryId ON dbo.Products(CategoryId);
    CREATE INDEX IX_Products_Name ON dbo.Products(Name);
END
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Orders
    (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Orders PRIMARY KEY,
        UserId NVARCHAR(50) NOT NULL,
        OrderDate DATETIME2 NOT NULL CONSTRAINT DF_Orders_OrderDate DEFAULT (SYSUTCDATETIME()),
        TotalAmount DECIMAL(18,2) NOT NULL CONSTRAINT DF_Orders_TotalAmount DEFAULT ((0)),
        Status NVARCHAR(50) NOT NULL CONSTRAINT DF_Orders_Status DEFAULT (N'Pending'),
        ShippingAddress NVARCHAR(500) NOT NULL CONSTRAINT DF_Orders_ShippingAddress DEFAULT (N''),
        PaymentMethod NVARCHAR(50) NOT NULL CONSTRAINT DF_Orders_PaymentMethod DEFAULT (N'counter'),
        PaymentStatus NVARCHAR(50) NOT NULL CONSTRAINT DF_Orders_PaymentStatus DEFAULT (N'PayAtCounter'),
        PaymentCode NVARCHAR(50) NOT NULL CONSTRAINT DF_Orders_PaymentCode DEFAULT (N''),
        PaymentNote NVARCHAR(500) NOT NULL CONSTRAINT DF_Orders_PaymentNote DEFAULT (N'Thanh toán trực tiếp tại quầy hoặc văn phòng khi đến nhận/xác nhận đơn.'),
        CONSTRAINT FK_Orders_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
        CONSTRAINT CK_Orders_Status CHECK (Status IN (N'Pending', N'Confirmed', N'Shipping', N'Completed', N'Cancelled'))
    );

    CREATE INDEX IX_Orders_UserId ON dbo.Orders(UserId);
    CREATE INDEX IX_Orders_OrderDate ON dbo.Orders(OrderDate DESC);
END
GO

IF OBJECT_ID(N'dbo.OrderDetails', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.OrderDetails
    (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_OrderDetails PRIMARY KEY,
        OrderId INT NOT NULL,
        ProductId INT NOT NULL,
        Quantity INT NOT NULL CONSTRAINT DF_OrderDetails_Quantity DEFAULT ((1)),
        UnitPrice DECIMAL(18,2) NOT NULL,
        CONSTRAINT FK_OrderDetails_Orders FOREIGN KEY (OrderId) REFERENCES dbo.Orders(Id) ON DELETE CASCADE,
        CONSTRAINT FK_OrderDetails_Products FOREIGN KEY (ProductId) REFERENCES dbo.Products(Id),
        CONSTRAINT CK_OrderDetails_Quantity CHECK (Quantity > 0)
    );

    CREATE INDEX IX_OrderDetails_OrderId ON dbo.OrderDetails(OrderId);
    CREATE INDEX IX_OrderDetails_ProductId ON dbo.OrderDetails(ProductId);
END
GO

IF OBJECT_ID(N'dbo.Reviews', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Reviews
    (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Reviews PRIMARY KEY,
        ProductId INT NOT NULL,
        UserId NVARCHAR(50) NOT NULL,
        Rating INT NOT NULL,
        Comment NVARCHAR(MAX) NOT NULL CONSTRAINT DF_Reviews_Comment DEFAULT (N''),
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_Reviews_CreatedDate DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_Reviews_Products FOREIGN KEY (ProductId) REFERENCES dbo.Products(Id),
        CONSTRAINT FK_Reviews_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
        CONSTRAINT CK_Reviews_Rating CHECK (Rating >= 1 AND Rating <= 5)
    );

    CREATE INDEX IX_Reviews_ProductId ON dbo.Reviews(ProductId);
    CREATE INDEX IX_Reviews_UserId ON dbo.Reviews(UserId);
END
GO

/* =========================================================
   System/configuration tables
   ========================================================= */

IF OBJECT_ID(N'dbo.Settings', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Settings
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_Settings PRIMARY KEY
            CONSTRAINT DF_Settings_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        IsOnline BIT NOT NULL CONSTRAINT DF_Settings_IsOnline DEFAULT ((1)),
        IsTwoCamera BIT NOT NULL CONSTRAINT DF_Settings_IsTwoCamera DEFAULT ((0)),
        JistiDomain NVARCHAR(255) NOT NULL CONSTRAINT DF_Settings_JistiDomain DEFAULT (N''),
        Name NVARCHAR(100) NOT NULL CONSTRAINT DF_Settings_Name DEFAULT (N'Default'),
        CreatedBy NVARCHAR(100) NOT NULL CONSTRAINT DF_Settings_CreatedBy DEFAULT (N'system'),
        Created DATETIME2 NOT NULL CONSTRAINT DF_Settings_Created DEFAULT (SYSUTCDATETIME()),
        ModifiedBy NVARCHAR(100) NULL,
        Modified DATETIME2 NULL,
        IsDeleted BIT NOT NULL CONSTRAINT DF_Settings_IsDeleted DEFAULT ((0)),
        IsActive BIT NOT NULL CONSTRAINT DF_Settings_IsActive DEFAULT ((1)),
        JistiDomainInternet NVARCHAR(255) NOT NULL CONSTRAINT DF_Settings_JistiDomainInternet DEFAULT (N''),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );
END
GO

IF OBJECT_ID(N'dbo.SeedConfigurations', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SeedConfigurations
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_SeedConfigurations PRIMARY KEY
            CONSTRAINT DF_SeedConfigurations_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        RightSeed DECIMAL(18,4) NOT NULL CONSTRAINT DF_SeedConfigurations_RightSeed DEFAULT ((0)),
        LeftSeed DECIMAL(18,4) NOT NULL CONSTRAINT DF_SeedConfigurations_LeftSeed DEFAULT ((0)),
        BackwardSeed DECIMAL(18,4) NOT NULL CONSTRAINT DF_SeedConfigurations_BackwardSeed DEFAULT ((0)),
        ForwardSeed DECIMAL(18,4) NOT NULL CONSTRAINT DF_SeedConfigurations_ForwardSeed DEFAULT ((0)),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );
END
GO

/* =========================================================
   Audit/log tables
   ========================================================= */

IF OBJECT_ID(N'dbo.LogActions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LogActions
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_LogActions PRIMARY KEY
            CONSTRAINT DF_LogActions_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Name NVARCHAR(200) NOT NULL CONSTRAINT DF_LogActions_Name DEFAULT (N''),
        Action NVARCHAR(500) NOT NULL CONSTRAINT DF_LogActions_Action DEFAULT (N''),
        IPAddress NVARCHAR(50) NOT NULL CONSTRAINT DF_LogActions_IPAddress DEFAULT (N''),
        LocalName NVARCHAR(200) NOT NULL CONSTRAINT DF_LogActions_LocalName DEFAULT (N''),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );
END
GO

IF OBJECT_ID(N'dbo.LogErrors', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LogErrors
    (
        Id NVARCHAR(50) NOT NULL
            CONSTRAINT PK_LogErrors PRIMARY KEY
            CONSTRAINT DF_LogErrors_Id DEFAULT (REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', '')),
        Header NVARCHAR(500) NOT NULL CONSTRAINT DF_LogErrors_Header DEFAULT (N''),
        Body NVARCHAR(MAX) NOT NULL CONSTRAINT DF_LogErrors_Body DEFAULT (N''),
        Message NVARCHAR(MAX) NOT NULL CONSTRAINT DF_LogErrors_Message DEFAULT (N''),
        CreatedDateTime DATETIME2 NULL,
        CreatedUser NVARCHAR(100) NULL
    );
END
GO

/* =========================================================
   Seed: roles, users, modules, functions
   ========================================================= */

DECLARE @AdminRoleId NVARCHAR(50) = N'role_admin';
DECLARE @UserRoleId NVARCHAR(50) = N'role_user';
DECLARE @ManagerRoleId NVARCHAR(50) = N'role_manager';
DECLARE @AdminUserId NVARCHAR(50) = N'user_admin';
DECLARE @NormalUserId NVARCHAR(50) = N'user_demo';
DECLARE @ManagerUserId NVARCHAR(50) = N'user_manager';

IF NOT EXISTS (SELECT 1 FROM dbo.Roles WHERE Id = @AdminRoleId)
BEGIN
    INSERT INTO dbo.Roles (Id, Guid, Name, Description, CreatedBy, Created, IsDeleted, IsActive, RoleType)
    VALUES
        (@AdminRoleId, NEWID(), N'Admin', N'Administrator with full access', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (@UserRoleId, NEWID(), N'User', N'Regular user with limited access', N'system', SYSUTCDATETIME(), 0, 1, 0),
        (@ManagerRoleId, NEWID(), N'Manager', N'Manager with moderate access', N'system', SYSUTCDATETIME(), 0, 1, 2);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE UserName = N'admin')
BEGIN
    INSERT INTO dbo.Users (Id, Name, UserName, Password, Salt, Contact, Email, Phone, Position, Image, IsActive, UserType, Created)
    VALUES
        (N'user_admin', N'Administrator', N'admin', N'admin123', NULL, N'', N'admin@basecore.local', N'0123456789', N'System Administrator', N'', 1, 1, SYSUTCDATETIME()),
        (N'user_demo', N'Demo User', N'demo', N'demo123', NULL, N'', N'demo@basecore.local', N'0900000001', N'Customer', N'', 1, 0, SYSUTCDATETIME()),
        (N'user_manager', N'Demo Manager', N'manager', N'manager123', NULL, N'', N'manager@basecore.local', N'0900000002', N'Store Manager', N'', 1, 2, SYSUTCDATETIME());
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.UserRoles WHERE UserId = N'user_admin' AND RoleId = N'role_admin')
BEGIN
    INSERT INTO dbo.UserRoles (Id, Guid, UserId, RoleId, IsActive, CreatedBy, Created, IsDeleted)
    VALUES
        (N'ur_admin_admin', NEWID(), N'user_admin', N'role_admin', 1, N'system', SYSUTCDATETIME(), 0),
        (N'ur_demo_user', NEWID(), N'user_demo', N'role_user', 1, N'system', SYSUTCDATETIME(), 0),
        (N'ur_manager_manager', NEWID(), N'user_manager', N'role_manager', 1, N'system', SYSUTCDATETIME(), 0);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.Modules)
BEGIN
    INSERT INTO dbo.Modules (Id, Guid, Name, Description, CreatedBy, Created, IsDeleted, IsActive, IsChecked)
    VALUES
        (N'module_dashboard', NEWID(), N'Dashboard', N'Overview and statistics', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_products', NEWID(), N'Products', N'Product management', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_categories', NEWID(), N'Categories', N'Category management', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_orders', NEWID(), N'Orders', N'Order management', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_users', NEWID(), N'Users', N'User management', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_roles', NEWID(), N'Roles', N'Role and permission management', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_settings', NEWID(), N'Settings', N'System settings', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'module_audit', NEWID(), N'AuditLogs', N'Audit and exception logs', N'system', SYSUTCDATETIME(), 0, 1, 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.Functions)
BEGIN
    INSERT INTO dbo.Functions (Id, Name, Description, CreatedBy, Created, IsDeleted, IsActive, IsChecked)
    VALUES
        (N'func_read', N'Read', N'Read/list/view data', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'func_create', N'Create', N'Create new data', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'func_update', N'Update', N'Update existing data', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'func_delete', N'Delete', N'Delete data', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'func_manage', N'Manage', N'Full management access', N'system', SYSUTCDATETIME(), 0, 1, 1),
        (N'func_checkout', N'Checkout', N'Create and manage own orders', N'system', SYSUTCDATETIME(), 0, 1, 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.ModuleFunctions)
BEGIN
    INSERT INTO dbo.ModuleFunctions (Id, Guid, ModuleId, FunctionId, CreatedBy, Created, IsDeleted)
    VALUES
        (N'mf_dashboard_read', NEWID(), N'module_dashboard', N'func_read', N'system', SYSUTCDATETIME(), 0),
        (N'mf_products_read', NEWID(), N'module_products', N'func_read', N'system', SYSUTCDATETIME(), 0),
        (N'mf_products_create', NEWID(), N'module_products', N'func_create', N'system', SYSUTCDATETIME(), 0),
        (N'mf_products_update', NEWID(), N'module_products', N'func_update', N'system', SYSUTCDATETIME(), 0),
        (N'mf_products_delete', NEWID(), N'module_products', N'func_delete', N'system', SYSUTCDATETIME(), 0),
        (N'mf_categories_read', NEWID(), N'module_categories', N'func_read', N'system', SYSUTCDATETIME(), 0),
        (N'mf_categories_create', NEWID(), N'module_categories', N'func_create', N'system', SYSUTCDATETIME(), 0),
        (N'mf_categories_update', NEWID(), N'module_categories', N'func_update', N'system', SYSUTCDATETIME(), 0),
        (N'mf_categories_delete', NEWID(), N'module_categories', N'func_delete', N'system', SYSUTCDATETIME(), 0),
        (N'mf_orders_read', NEWID(), N'module_orders', N'func_read', N'system', SYSUTCDATETIME(), 0),
        (N'mf_orders_checkout', NEWID(), N'module_orders', N'func_checkout', N'system', SYSUTCDATETIME(), 0),
        (N'mf_orders_update', NEWID(), N'module_orders', N'func_update', N'system', SYSUTCDATETIME(), 0),
        (N'mf_users_read', NEWID(), N'module_users', N'func_read', N'system', SYSUTCDATETIME(), 0),
        (N'mf_users_create', NEWID(), N'module_users', N'func_create', N'system', SYSUTCDATETIME(), 0),
        (N'mf_users_update', NEWID(), N'module_users', N'func_update', N'system', SYSUTCDATETIME(), 0),
        (N'mf_users_delete', NEWID(), N'module_users', N'func_delete', N'system', SYSUTCDATETIME(), 0),
        (N'mf_roles_manage', NEWID(), N'module_roles', N'func_manage', N'system', SYSUTCDATETIME(), 0),
        (N'mf_settings_manage', NEWID(), N'module_settings', N'func_manage', N'system', SYSUTCDATETIME(), 0),
        (N'mf_audit_read', NEWID(), N'module_audit', N'func_read', N'system', SYSUTCDATETIME(), 0);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.RoleModules)
BEGIN
    INSERT INTO dbo.RoleModules (RoleId, ModuleId)
    SELECT r.Id, m.Id
    FROM dbo.Roles r
    CROSS JOIN dbo.Modules m
    WHERE r.Id = N'role_admin';

    INSERT INTO dbo.RoleModules (RoleId, ModuleId)
    SELECT N'role_manager', m.Id
    FROM dbo.Modules m
    WHERE m.Id IN (N'module_dashboard', N'module_products', N'module_categories', N'module_orders', N'module_audit');

    INSERT INTO dbo.RoleModules (RoleId, ModuleId)
    SELECT N'role_user', m.Id
    FROM dbo.Modules m
    WHERE m.Id IN (N'module_dashboard', N'module_products', N'module_categories', N'module_orders');
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.RoleModuleFunctions)
BEGIN
    INSERT INTO dbo.RoleModuleFunctions (Id, Guid, RoleId, ModuleFunctionId, CreatedBy, Created, IsDeleted, IsActive)
    SELECT
        CONCAT(N'rmf_admin_', REPLACE(mf.Id, N'mf_', N'')),
        NEWID(),
        N'role_admin',
        mf.Id,
        N'system',
        SYSUTCDATETIME(),
        0,
        1
    FROM dbo.ModuleFunctions mf;

    INSERT INTO dbo.RoleModuleFunctions (Id, Guid, RoleId, ModuleFunctionId, CreatedBy, Created, IsDeleted, IsActive)
    SELECT
        CONCAT(N'rmf_manager_', REPLACE(mf.Id, N'mf_', N'')),
        NEWID(),
        N'role_manager',
        mf.Id,
        N'system',
        SYSUTCDATETIME(),
        0,
        1
    FROM dbo.ModuleFunctions mf
    WHERE mf.Id IN
    (
        N'mf_dashboard_read',
        N'mf_products_read', N'mf_products_create', N'mf_products_update',
        N'mf_categories_read', N'mf_categories_create', N'mf_categories_update',
        N'mf_orders_read', N'mf_orders_update', N'mf_orders_checkout',
        N'mf_audit_read'
    );

    INSERT INTO dbo.RoleModuleFunctions (Id, Guid, RoleId, ModuleFunctionId, CreatedBy, Created, IsDeleted, IsActive)
    SELECT
        CONCAT(N'rmf_user_', REPLACE(mf.Id, N'mf_', N'')),
        NEWID(),
        N'role_user',
        mf.Id,
        N'system',
        SYSUTCDATETIME(),
        0,
        1
    FROM dbo.ModuleFunctions mf
    WHERE mf.Id IN
    (
        N'mf_dashboard_read',
        N'mf_products_read',
        N'mf_categories_read',
        N'mf_orders_read',
        N'mf_orders_checkout'
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.UserModules)
BEGIN
    INSERT INTO dbo.UserModules (Id, Guid, UserId, ModuleId, CreatedBy, Created, IsDeleted)
    SELECT
        CONCAT(N'um_', u.Id, N'_', m.Id),
        NEWID(),
        u.Id,
        m.Id,
        N'system',
        SYSUTCDATETIME(),
        0
    FROM dbo.Users u
    INNER JOIN dbo.RoleModules rm
        ON rm.RoleId = CASE u.UserType
            WHEN 1 THEN N'role_admin'
            WHEN 2 THEN N'role_manager'
            ELSE N'role_user'
        END
    INNER JOIN dbo.Modules m
        ON m.Id = rm.ModuleId;
END
GO

/* =========================================================
   Seed: system configuration
   ========================================================= */

IF NOT EXISTS (SELECT 1 FROM dbo.Settings)
BEGIN
    INSERT INTO dbo.Settings
    (
        Id, IsOnline, IsTwoCamera, JistiDomain, Name, CreatedBy, Created,
        IsDeleted, IsActive, JistiDomainInternet
    )
    VALUES
    (
        N'setting_default', 1, 0, N'meet.basecore.local', N'Default system setting',
        N'system', SYSUTCDATETIME(), 0, 1, N'meet.basecore.local'
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SeedConfigurations)
BEGIN
    INSERT INTO dbo.SeedConfigurations
    (
        Id, RightSeed, LeftSeed, BackwardSeed, ForwardSeed, CreatedDateTime, CreatedUser
    )
    VALUES
    (
        N'seed_default', 1.0000, 1.0000, 1.0000, 1.0000, SYSUTCDATETIME(), N'system'
    );
END
GO

/* =========================================================
   Seed: categories and products
   ========================================================= */

DECLARE @CategorySeeds TABLE
(
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NOT NULL
);

INSERT INTO @CategorySeeds (Name, Description)
VALUES
    (N'Điện thoại', N'Điện thoại thông minh chính hãng, cấu hình mạnh và camera chất lượng.'),
    (N'Laptop', N'Laptop phục vụ học tập, văn phòng, đồ họa và gaming.'),
    (N'Smartwatch', N'Đồng hồ thông minh theo dõi sức khỏe, luyện tập và thông báo.'),
    (N'Tablet', N'Máy tính bảng cho học tập, giải trí, ghi chú và làm việc di động.');

DECLARE @LegacyCategoryMap TABLE
(
    OldName NVARCHAR(100) NOT NULL,
    NewName NVARCHAR(100) NOT NULL
);

INSERT INTO @LegacyCategoryMap (OldName, NewName)
VALUES
    (N'Electronics', N'Điện thoại'),
    (N'Clothing', N'Laptop'),
    (N'Books', N'Smartwatch'),
    (N'Home & Garden', N'Tablet');

UPDATE c
SET
    c.Name = lcm.NewName,
    c.Description = cs.Description
FROM dbo.Categories c
INNER JOIN @LegacyCategoryMap lcm
    ON lcm.OldName = c.Name
INNER JOIN @CategorySeeds cs
    ON cs.Name = lcm.NewName
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.Categories existing
    WHERE existing.Name = lcm.NewName
      AND existing.Id <> c.Id
);

INSERT INTO dbo.Categories (Name, Description)
SELECT cs.Name, cs.Description
FROM @CategorySeeds cs
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.Categories c
    WHERE c.Name = cs.Name
);

UPDATE c
SET c.Description = cs.Description
FROM dbo.Categories c
INNER JOIN @CategorySeeds cs
    ON cs.Name = c.Name;
GO

DECLARE @ProductSeeds TABLE
(
    Name NVARCHAR(200) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    Stock INT NOT NULL,
    CategoryName NVARCHAR(100) NOT NULL,
    Description NVARCHAR(1000) NOT NULL,
    ImageUrl NVARCHAR(500) NOT NULL
);

INSERT INTO @ProductSeeds (Name, Price, Stock, CategoryName, Description, ImageUrl)
VALUES
    (N'iPhone 15 Pro', 28000000, 15, N'Điện thoại', N'Điện thoại cao cấp với chip A17 Pro, camera tốt và hiệu năng mạnh.', N''),
    (N'Samsung Galaxy S24 Ultra', 26500000, 12, N'Điện thoại', N'Flagship Android với bút S Pen, màn hình lớn và camera zoom sắc nét.', N''),
    (N'Xiaomi 14', 18990000, 18, N'Điện thoại', N'Điện thoại nhỏ gọn, hiệu năng cao, sạc nhanh và camera Leica.', N''),
    (N'OPPO Reno 11 5G', 10990000, 24, N'Điện thoại', N'Mẫu điện thoại tầm trung nổi bật với thiết kế mỏng và chụp chân dung đẹp.', N''),
    (N'Laptop Dell XPS 15', 35000000, 10, N'Laptop', N'Laptop màn hình 15 inch, phù hợp cho học tập và công việc nặng.', N''),
    (N'MacBook Air M3', 31990000, 14, N'Laptop', N'Laptop mỏng nhẹ, pin lâu, phù hợp học tập, văn phòng và sáng tạo nội dung.', N''),
    (N'ASUS ROG Zephyrus G14', 39990000, 8, N'Laptop', N'Laptop gaming nhỏ gọn với hiệu năng mạnh cho game và đồ họa.', N''),
    (N'Lenovo ThinkPad X1 Carbon', 42990000, 9, N'Laptop', N'Laptop doanh nhân bền nhẹ, bàn phím tốt và bảo mật cao.', N''),
    (N'Apple Watch Series 9', 10990000, 18, N'Smartwatch', N'Đồng hồ thông minh theo dõi sức khỏe và thông báo hằng ngày.', N''),
    (N'Samsung Galaxy Watch 6', 7490000, 20, N'Smartwatch', N'Đồng hồ Android theo dõi luyện tập, giấc ngủ và sức khỏe tổng quát.', N''),
    (N'Garmin Venu 3', 10990000, 11, N'Smartwatch', N'Smartwatch thể thao với GPS chính xác và pin dùng nhiều ngày.', N''),
    (N'Xiaomi Watch 2 Pro', 6490000, 16, N'Smartwatch', N'Đồng hồ thông minh Wear OS, hỗ trợ nhiều chế độ luyện tập.', N''),
    (N'iPad Air M2', 18900000, 14, N'Tablet', N'Máy tính bảng gọn nhẹ cho học tập, giải trí và ghi chú.', N''),
    (N'Samsung Galaxy Tab S9', 19990000, 13, N'Tablet', N'Tablet Android cao cấp với màn hình AMOLED và bút S Pen.', N''),
    (N'Xiaomi Pad 6', 8990000, 22, N'Tablet', N'Tablet giá tốt với màn hình tần số quét cao và hiệu năng ổn định.', N''),
    (N'Lenovo Tab P12', 11990000, 17, N'Tablet', N'Tablet màn hình lớn phục vụ học online, xem phim và làm việc nhẹ.', N'');

UPDATE @ProductSeeds
SET ImageUrl = CONCAT(
    N'https://tse.mm.bing.net/th?w=360&h=360&c=7&rs=1&p=0&dpr=1&pid=1.7&mkt=vi-VN&q=',
    REPLACE(Name, N' ', N'%20'),
    N'%20official%20product%20photo'
)
WHERE ImageUrl = N'';

DECLARE @ObsoleteProductSeeds TABLE
(
    Name NVARCHAR(200) NOT NULL
);

INSERT INTO @ObsoleteProductSeeds (Name)
VALUES
    (N'Sony WH-1000XM5'),
    (N'Ao Thun Cotton Premium'),
    (N'Ao Hoodie Basic'),
    (N'Quan Jean Slim Fit'),
    (N'Clean Code'),
    (N'ASP.NET Core Thuc Chien'),
    (N'Noi Chien Khong Dau 6L'),
    (N'Den Ban LED Thong Minh'),
    (N'Bo Dung Cu Lam Vuon'),
    (N'Tham Yoga Cao Su'),
    (N'Ta Tay 10kg'),
    (N'Vot Cau Long Carbon'),
    (N'T-Shirt Cotton'),
    (N'Programming Book'),
    (N'Garden Tools Set');

DELETE p
FROM dbo.Products p
INNER JOIN @ObsoleteProductSeeds ops
    ON ops.Name = p.Name
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.OrderDetails od
    WHERE od.ProductId = p.Id
);

UPDATE p
SET
    p.Price = ps.Price,
    p.Stock = ps.Stock,
    p.CategoryId = c.Id,
    p.Description = ps.Description,
    p.ImageUrl = ps.ImageUrl
FROM dbo.Products p
INNER JOIN @ProductSeeds ps
    ON ps.Name = p.Name
INNER JOIN dbo.Categories c
    ON c.Name = ps.CategoryName;

INSERT INTO dbo.Products (Name, Price, Stock, CategoryId, Description, ImageUrl)
SELECT
    ps.Name,
    ps.Price,
    ps.Stock,
    c.Id,
    ps.Description,
    ps.ImageUrl
FROM @ProductSeeds ps
INNER JOIN dbo.Categories c
    ON c.Name = ps.CategoryName
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.Products p
    WHERE p.Name = ps.Name
);

DECLARE @ObsoleteCategorySeeds TABLE
(
    Name NVARCHAR(100) NOT NULL
);

INSERT INTO @ObsoleteCategorySeeds (Name)
VALUES
    (N'Electronics'),
    (N'Clothing'),
    (N'Books'),
    (N'Home & Garden'),
    (N'Sports');

DELETE c
FROM dbo.Categories c
INNER JOIN @ObsoleteCategorySeeds ocs
    ON ocs.Name = c.Name
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.Products p
    WHERE p.CategoryId = c.Id
);
GO

/* =========================================================
   Seed: agency groups and logs
   ========================================================= */

IF NOT EXISTS (SELECT 1 FROM dbo.GroupRoleAgencies)
BEGIN
    INSERT INTO dbo.GroupRoleAgencies
    (
        Id, Guid, AgencyId, Name, Description, CreatedBy, Created,
        IsDeleted, IsActive, RoleType
    )
    VALUES
    (
        N'gra_default', NEWID(), N'agency_default', N'Default agency role group',
        N'Default group for tenant/agency based role mapping',
        N'system', SYSUTCDATETIME(), 0, 1, 0
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.GroupRoleAgencyModules)
BEGIN
    INSERT INTO dbo.GroupRoleAgencyModules (GroupRoleAgencyId, ModuleId)
    SELECT N'gra_default', Id
    FROM dbo.Modules
    WHERE Id IN (N'module_dashboard', N'module_products', N'module_categories', N'module_orders');
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.LogActions)
BEGIN
    INSERT INTO dbo.LogActions (Id, Name, Action, IPAddress, LocalName, CreatedDateTime, CreatedUser)
    VALUES
        (N'logaction_bootstrap', N'System bootstrap', N'Initial database seed completed', N'127.0.0.1', N'BaseCoreSales', SYSUTCDATETIME(), N'system');
END
GO

PRINT N'BaseCoreSales database script completed successfully.';
GO

